"""Frida hook and Interceptor template generators.

Phase 2 ships two template generators that produce ready-to-run
JavaScript source code for Frida. The templates include the function
argument read-out, return-value capture, and a backtrace option.
"""

from __future__ import annotations

from typing import Annotated, Any

from mcp.server.fastmcp import FastMCP  # type: ignore[import-untyped]
from pydantic import Field

__all__ = ["register"]


def register(mcp: FastMCP) -> None:
    """Register hook template generators."""

    @mcp.tool(
        name="generate_frida_native_hook",
        description=(
            "Generate a Frida hook script for a native function. The "
            "script uses ``Interceptor.attach`` and reads arguments + "
            "return value. Use this output with android-re-dynamic's "
            "``frida_load_script`` tool (Phase 3) or with the frida CLI."
        ),
    )
    def generate_frida_native_hook(
        module: Annotated[str, Field(description="Module name, e.g. 'libfoo.so'")],
        symbol: Annotated[
            str, Field(description="Symbol to hook, e.g. 'Java_com_example_Foo_bar'")
        ],
        backtrace: Annotated[bool, Field(description="Include a backtrace on entry")] = False,
        log_args: Annotated[bool, Field(description="Print function arguments")] = True,
        log_ret: Annotated[bool, Field(description="Print function return value")] = True,
    ) -> dict[str, Any]:
        script = _render_hook(
            module, symbol, backtrace=backtrace, log_args=log_args, log_ret=log_ret
        )
        return {
            "module": module,
            "symbol": symbol,
            "script": script,
        }

    @mcp.tool(
        name="generate_native_interceptor",
        description=(
            "Generate a JavaScript template that uses "
            "``Interceptor.attach`` with a custom return-value override. "
            "Useful for functions that gate access (root checks, "
            "license checks, etc.)."
        ),
    )
    def generate_native_interceptor(
        module: Annotated[str, Field(description="Module name, e.g. 'libfoo.so'")],
        symbol: Annotated[str, Field(description="Symbol to intercept")],
        return_value: Annotated[
            str,
            Field(
                description=(
                    "JavaScript expression for the return value, e.g. "
                    "'0' (zero), '1' (one), 'ptr(\"0x1234\")' (a pointer)"
                )
            ),
        ] = "0",
    ) -> dict[str, Any]:
        script = _render_interceptor(module, symbol, return_value)
        return {
            "module": module,
            "symbol": symbol,
            "script": script,
        }


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------


_HOOK_TEMPLATE = """\
// Generated by android-re-mcp-native / generate_frida_native_hook
// Module: {module}
// Symbol: {symbol}

const moduleName = "{module}";
const symbolName = "{symbol}";

const target = Module.findExportByName(moduleName, symbolName);
if (target === null) {{
  console.error("[-] symbol not found:", moduleName, symbolName);
}} else {{
  console.log("[+] hooking", moduleName + "!" + symbolName, "at", target);
  Interceptor.attach(target, {{
    onEnter(args) {{
      console.log("[*]", symbolName, "called");
{args_block}
{backtrace_block}
    }},
    onLeave(retval) {{
{ret_block}
      retval.replace(0);
    }},
  }});
}}
"""

_INTERCEPTOR_TEMPLATE = """\
// Generated by android-re-mcp-native / generate_native_interceptor
// Module: {module}
// Symbol: {symbol}
// Forced return: {return_value}

const moduleName = "{module}";
const symbolName = "{symbol}";

const target = Module.findExportByName(moduleName, symbolName);
if (target === null) {{
  console.error("[-] symbol not found:", moduleName, symbolName);
}} else {{
  console.log("[+] intercepting", moduleName + "!" + symbolName, "at", target);
  Interceptor.attach(target, {{
    onEnter(args) {{
      console.log("[*]", symbolName, "called (forcing return {return_value})");
    }},
    onLeave(retval) {{
      retval.replace({return_value});
    }},
  }});
}}
"""


def _render_hook(
    module: str,
    symbol: str,
    *,
    backtrace: bool,
    log_args: bool,
    log_ret: bool,
) -> str:
    args_block = ""
    if log_args:
        # Read up to 8 arguments; print each pointer + a try-as-string.
        args_lines: list[str] = []
        for i in range(8):
            args_lines.append(
                f'      try {{ console.log("    arg{i}:", args[{i}]); '
                f'console.log("      as str:", args[{i}].readCString()); }} '
                f"catch (e) {{ /* ignore non-pointer */ }}"
            )
        args_block = "\n".join(args_lines)
    backtrace_block = ""
    if backtrace:
        backtrace_block = "      console.log(Thread.backtrace(this.context, Backtracer.ACCURATE).map(DebugSymbol.fromAddress).join('\\n'));"
    ret_block = ""
    if log_ret:
        ret_block = '      console.log("[ret]", symbolName, "=>", retval);'
    return _HOOK_TEMPLATE.format(
        module=module,
        symbol=symbol,
        args_block=args_block,
        backtrace_block=backtrace_block,
        ret_block=ret_block,
    )


def _render_interceptor(module: str, symbol: str, return_value: str) -> str:
    return _INTERCEPTOR_TEMPLATE.format(
        module=module,
        symbol=symbol,
        return_value=return_value,
    )
