#!/usr/bin/env bash
# Generated by scripts/lib/render_seed.py — do not edit by hand.
# Edit templates/seeds/seed-issues.sh.j2 instead.
#
# Mirrors the canonical seed in https://github.com/Heretek-AI/monorepo-manager
# into the GitHub Issues of Heretek-AI/llama-builds.
#
# Self-contained: the child repo does NOT ship a copy of
# `scripts.lib.seed_loader`. Body markdown is emitted by the heredoc
# below; seed structural validation is done with `yq` (already required).
set -euo pipefail

ORG_DEFAULT="Heretek-AI"
REPO_DEFAULT="llama-builds"
SLUG="llama-builds"
SEED_URL_DEFAULT="https://raw.githubusercontent.com/${ORG_DEFAULT}/monorepo-manager/main/seeds/${SLUG}.yaml"
SEED_FILE_DEFAULT=""
LABELS_FILE_DEFAULT="./.github/labels/labels.yaml"
CACHE_DIR="${HOME}/.cache/heretek-seed"
CACHE_FILE="${CACHE_DIR}/${SLUG}.json"

usage() {
  cat <<EOF
Usage: seed-issues.sh --repo OWNER/REPO [--seed-url URL | --seed-file PATH]
                      [--labels-file PATH]
                      [--id ID] [--dry-run] [--only-labels] [--prune-closed]
EOF
}

REPO="${ORG_DEFAULT}/${REPO_DEFAULT}"
SEED_URL="${SEED_URL_DEFAULT}"
SEED_FILE="${SEED_FILE_DEFAULT}"
LABELS_FILE="${LABELS_FILE_DEFAULT}"
ONLY_ID=""
DRY_RUN="no"
ONLY_LABELS="no"
PRUNE_CLOSED="no"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --seed-url) SEED_URL="$2"; shift 2 ;;
    --seed-file) SEED_FILE="$2"; shift 2 ;;
    --labels-file) LABELS_FILE="$2"; shift 2 ;;
    --id) ONLY_ID="$2"; shift 2 ;;
    --dry-run) DRY_RUN="yes"; shift ;;
    --only-labels) ONLY_LABELS="yes"; shift ;;
    --prune-closed) PRUNE_CLOSED="yes"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

# --- step 1: preflight ---
if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI not found in PATH" >&2
  exit 3
fi
# Skip gh auth check on --dry-run so the script can complete without credentials.
if [[ "${DRY_RUN}" != "yes" ]] && ! gh auth status >/dev/null 2>&1; then
  echo "gh is not authenticated; run: gh auth login" >&2
  exit 4
fi
if ! command -v yq >/dev/null 2>&1; then
  echo "yq CLI not found in PATH" >&2
  exit 3
fi

# --- step 2: fetch the seed ---
mkdir -p "${CACHE_DIR}"
if [[ -n "${SEED_FILE}" ]]; then
  SEED_PATH="${SEED_FILE}"
else
  SEED_PATH="${CACHE_DIR}/${SLUG}.seed.yaml"
  curl -fsSL --retry 3 --retry-delay 5 -o "${SEED_PATH}" "${SEED_URL}" || {
    echo "failed to fetch seed from ${SEED_URL}" >&2
    exit 5
  }
fi

# --- step 2a: validate the seed with yq (no python dependency) ---
if [[ "$(yq eval '.schema_version // 0' "${SEED_PATH}" 2>/dev/null)" != "1" ]]; then
  echo "seed validation failed: schema_version != 1; aborting before any gh call" >&2
  exit 6
fi
if [[ "$(yq eval '.issues | length' "${SEED_PATH}" 2>/dev/null)" -lt 1 ]]; then
  echo "seed validation failed: no issues; aborting before any gh call" >&2
  exit 6
fi

# --- step 2b: sync labels from --labels-file (NOT from the seed) ---
if [[ ! -f "${LABELS_FILE}" ]]; then
  echo "labels file not found: ${LABELS_FILE} (pass --labels-file to override)" >&2
  exit 6
fi
while IFS=$'\t' read -r name color desc; do
  [[ -z "${name:-}" ]] && continue
  if [[ "${DRY_RUN}" == "yes" ]]; then
    echo "would: gh label create --force ${name} --color ${color} --description ${desc}"
  else
    gh label create "${name}" --color "${color}" --description "${desc}" --force >/dev/null
  fi
done < <(yq eval -o=tsv '.labels[] | [.name, .color, .description] | @tsv' "${LABELS_FILE}")

# --- step 3: one-shot discovery (--limit 1000) ---
# Build a single JSON array of every open+closed issue, then index by seed-id
# in the Python step below. This replaces the old per-issue `gh issue list`
# loop which made N round trips.
DISCOVERY_JSON="[]"
SEED_JSON="[]"
if [[ "${ONLY_LABELS}" != "yes" ]]; then
  if [[ "${DRY_RUN}" != "yes" ]]; then
    DISCOVERY_JSON=$(gh issue list --repo "${REPO}" --state all --limit 1000 \
        --json number,body,state,labels 2>/dev/null) || {
      echo "gh issue list failed" >&2
      exit 7
    }
  fi
  # Convert the seed YAML to JSON via yq so the embedded Python can read it
  # with stdlib `json` — no PyYAML dependency on the child repo.
  SEED_JSON=$(yq eval -o=json '.' "${SEED_PATH}")
fi

# --- helpers ---
# emit_body <id> prints the 5-section markdown body for one seed entry.
# Reproduces the structure produced by scripts.lib.seed_loader.emit_body_markdown
# so the on-disk issue body is byte-stable across the umbrella and child paths.
emit_body() {
  local id="$1"
  local doc section goal repo_name
  doc=$(yq eval ".issues[] | select(.id == \"$id\") | .source.doc" "${SEED_PATH}")
  section=$(yq eval ".issues[] | select(.id == \"$id\") | .source.section" "${SEED_PATH}")
  goal=$(yq eval ".issues[] | select(.id == \"$id\") | .goal" "${SEED_PATH}")
  repo_name="${REPO}"
  local acc oos deps
  acc=$(yq eval ".issues[] | select(.id == \"$id\") | .acceptance[]" "${SEED_PATH}" \
        | sed 's/^/- [ ] /' | sed '/^$/d')
  oos=$(yq eval ".issues[] | select(.id == \"$id\") | .out_of_scope[]" "${SEED_PATH}" 2>/dev/null \
        | sed 's/^/- /' | sed '/^$/d')
  deps=$(yq eval ".issues[] | select(.id == \"$id\") | .depends_on[]" "${SEED_PATH}" 2>/dev/null \
        | sed 's/^/- `/' | sed 's/$/`/' | sed '/^$/d')
  cat <<EOF
<!-- seed-id: ${id} -->
## Source
- Doc: \`${doc}\`
- Section: ${section}
- Repo: ${repo_name}

## Goal
${goal}

## Acceptance criteria
${acc:-(none)}

## Out of scope
${oos:-_None._}

## Dependencies
${deps:-_None._}

---
_Filed by scripts/seed-issues.sh from seeds/${SLUG}.yaml. Re-running the script with the same seed is idempotent (issues are matched by seed-id: <id> HTML comment at the top)._
EOF
}
export -f emit_body

# --- step 4: diff + create/update ---
if [[ "${ONLY_LABELS}" == "yes" ]]; then
  echo "only-labels: label sync complete, skipping issue sync"
  exit 0
fi
export REPO SEED_PATH CACHE_FILE ONLY_ID DRY_RUN PRUNE_CLOSED DISCOVERY_JSON SEED_JSON SLUG
python3 - <<'PYEOF' || exit 7
import json, hashlib, os, re, subprocess, sys
from pathlib import Path

cache_path = Path(os.environ["CACHE_FILE"])
cache_path.parent.mkdir(parents=True, exist_ok=True)
cache = json.loads(cache_path.read_text()) if cache_path.exists() else {}
state = cache.get("by_id", {})

# Use SEED_JSON (converted from YAML by yq) so we avoid the PyYAML dependency
# on the child repo. Only stdlib `json` is required.
seed = json.loads(os.environ["SEED_JSON"])

repo = os.environ["REPO"]
slug = os.environ["SLUG"]
only_id = os.environ["ONLY_ID"]
dry_run = os.environ["DRY_RUN"] == "yes"
prune_closed = os.environ["PRUNE_CLOSED"] == "yes"

# Build seed-id -> existing issue index from the one-shot discovery call.
existing = {}
for issue in json.loads(os.environ["DISCOVERY_JSON"]):
    body = issue.get("body", "") or ""
    m = re.search(r"<!-- seed-id:\s*([a-z]{2}-[0-9]{4})\s*-->", body)
    if m:
        existing[m.group(1)] = issue

created = updated = skipped = failed = 0

def body_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]

def run(cmd, **kw):
    if dry_run:
        print(f"would: {' '.join(cmd)}")
        return subprocess.CompletedProcess(cmd, 0, "", "")
    kw.setdefault("capture_output", True)
    kw.setdefault("text", True)
    return subprocess.run(cmd, **kw)

def emit_body_md(issue_id: str) -> str:
    # Defer to the bash heredoc; this keeps the body definition in one place
    # and matches what scripts.lib.seed_loader.emit_body_markdown would emit.
    out = subprocess.run(
        ["bash", "-c", f"emit_body {issue_id}"],
        capture_output=True, text=True,
    )
    return out.stdout

for issue in seed["issues"]:
    id_ = issue["id"]
    if only_id and id_ != only_id:
        continue
    body = emit_body_md(id_)
    bh = body_hash(body)
    phase = issue["phase"]; component = issue["component"]; status = issue["status"]
    title = issue["title"]
    if id_ in existing:
        ei = existing[id_]
        if ei["state"] == "closed" and not prune_closed:
            print(f"skip (closed): {id_}")
            skipped += 1
            continue
        prev_bh = state.get(id_, {}).get("body_hash")
        if prev_bh == bh and ei["state"] == "open":
            print(f"skip (unchanged): {id_}")
            skipped += 1
            continue
        r = run(["gh", "issue", "edit", str(ei["number"]),
                 "--repo", repo, "--body-file", "-"],
                input=body)
        if r.returncode != 0:
            failed += 1
            continue
        updated += 1
        state[id_] = {"body_hash": bh, "number": ei["number"]}
    else:
        r = run(["gh", "issue", "create", "--repo", repo,
                 "--title", title, "--body-file", "-",
                 "--label", phase, "--label", component, "--label", status],
                input=body)
        if r.returncode != 0:
            print(f"create failed for {id_}: {r.stderr}", file=sys.stderr)
            failed += 1
            continue
        m = re.search(r"/issues/(\d+)", r.stdout)
        number = int(m.group(1)) if m else None
        state[id_] = {"body_hash": bh, "number": number}
        created += 1

cache_path.write_text(json.dumps({"by_id": state}, indent=2, sort_keys=True))
print(f"created={created} updated={updated} skipped={skipped} failed={failed}")
sys.exit(0 if failed == 0 else 1)
PYEOF
